### ISSUE TITLE
你好请问benchmark TCMSD	TCMSD-BC TCMDD是否会开源？

### ISSUE THREAD

**Issue by sunzhaoyang1** [QLU-NLP/BianCang#1]

**Comment by WeiSibo** [comment]
TCMSD和TCMDD的原始数据集可以在下方链接中获取：https://github.com/Borororo/ZY-BERT

**Comment by sunzhaoyang1** [comment]
> TCMSD和TCMDD的原始数据集可以在下方链接中获取：https://github.com/Borororo/ZY-BERT

好的谢谢，但是我看论文中提到对原始的数据集进行了修改

**Comment by WeiSibo** [comment]
> > TCMSD和TCMDD的原始数据集可以在下方链接中获取：https://github.com/Borororo/ZY-BERT
> 
> 好的谢谢，但是我看论文中提到对原始的数据集进行了修改

对于测试集，可以参考论文附录的prompt template去构建query，response在原始数据集中抽取。处理后的训练集我们会在后续放出。

**Comment by sunzhaoyang1** [comment]
> > > TCMSD和TCMDD的原始数据集可以在下方链接中获取：https://github.com/Borororo/ZY-BERT
> > 
> > 
> > 好的谢谢，但是我看论文中提到对原始的数据集进行了修改
> 
> 对于测试集，可以参考论文附录的prompt template去构建query，response在原始数据集中抽取。处理后的训练集我们会在后续放出。

好的感谢，我以为是对辩证的label进行了重新标注和筛选。

**Comment by 0awei0** [comment]
你好，请问对于证型区分任务，sft阶段的数据集来自tcmsd，这里用于微调的数据的输出是什么呢，就是tcmsd原始的证型吗。

**Comment by WeiSibo** [comment]
> 你好，请问对于证型区分任务，sft阶段的数据集来自tcmsd，这里用于微调的数据的输出是什么呢，就是tcmsd原始的证型吗。

对于TCMSD：输出的关键内容包括证型和疾病。                                                                                                                                 对于TCMSD-BC：输出的关键内容除了证型和疾病外，还有辨病辨证的依据和分析。

**Comment by 0awei0** [comment]
您好，请问您打算单独开源继续预训练阶段得到的模型权重吗，我们没有资源做继续预训练，但是想引入自己的监督微调，非常感谢

**Comment by WeiSibo** [comment]
> 您好，请问您打算单独开源继续预训练阶段得到的模型权重吗，我们没有资源做继续预训练，但是想引入自己的监督微调，非常感谢

预训练阶段得到的模型权重已经公开在了Huggingface和Modelscope上，模型名中不带Instruct的模型（BianCang-Qwen2-7B、BianCang-Qwen2.5-7B）即为持续预训练模型，您可以直接进行下载。

**Comment by 0awei0** [comment]
非常感谢您的开源，十分感谢

**Comment by 0awei0** [comment]
请问在TCMSD-BC中，辨病辨证的依据和分析是怎么生成的呢，数据大概有多少条

**Comment by WeiSibo** [comment]
> 请问在TCMSD-BC中，辨病辨证的依据和分析是怎么生成的呢，数据大概有多少条

辨病辨证的依据和分析是从真实医院病历中提取的。数据量可以参考我们论文的表格。
